# Generated by cucumber-sinatra. (2014-10-04 10:06:04 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app/router.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Play

class PlayWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  PlayWorld.new
end
